name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install base dependencies first
          pip install -r requirements.txt
          # Install development dependencies
          pip install -r requirements-dev.txt
          # Force install specific versions of sympy and mathematics_dataset
          pip install --no-deps sympy==1.6.2
          pip install --no-deps mathematics_dataset==1.0
          # Install package in development mode
          pip install -e .
          # Verify sympy version
          python -c "import sympy; print(f'Installed sympy version: {sympy.__version__}')"

      - name: Run tests
        run: |
          python -m pytest

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: pytest-results.xml
